name: redismultiplexer
base: core20
version: '1.0.6'
summary: A flexible Redis queue manager written in Rust
description: |
  RedisMultiplexer will take care of your queues in Redis.
  The purpose is to move packages from a source queue to
  a target queue that may be or not be in the same server
  and port.
icon: redismultiplexer.png
license: Apache-2.0
website: https://www.juanmitaboada.com/
contact: https://www.juanmitaboada.com/contact/

grade: stable
confinement: classic

architectures:
  - amd64

parts:
  redismultiplexer:
    plugin: rust
    source: https://github.com/juanmitaboada/redismultiplexer.git
    build-packages:
      - pkg-config
      - librust-openssl-dev

apps:
  redismultiplexer:
    command: bin/redismultiplexer
    plugs:
      - home
      - network
